
name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
      
      - name: Clone project into this runner
        uses: actions/checkout@v3

      - name: Build Image from Dockerfile (source code )
        run: docker build -t my-image .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Image 
        run: docker tag my-image assidiwassimdev/my-image-cicd:latest

      - name: Push Image to DockerHub
        run: docker push assidiwassimdev/my-image-cicd:latest

  deploy-to-ec2: 

    runs-on: ubuntu-latest

    needs: build-and-push

    steps:
      
    - name: Deploy to EC2 AWS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
            sudo docker pull assidiwassimdev/my-image-cicd:latest
            sudo docker stop nodejs-container 
            sudo docker rm nodejs-container 
            sudo docker run -d --name nodejs-container -p 3001:3000 assidiwassimdev/my-image-cicd:latest